# Generated by Django 3.1.2 on 2020-10-15 14:14

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_default', models.TextField()),
                ('body_editorjs', django_editorjs_fields.fields.EditorJsJSONField()),
                ('body_custom', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('body_textfield', django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True)),
            ],
        ),
    ]
